### ISSUE TITLE
[Bug] store.get is not a function

### ISSUE THREAD

**Issue by rivaslive** [maxpert/node-cache-manager-sqlite#3]
This error is happend

```js
const cacheCollectionSQLiteStore = cacheManager.caching({
  store: sqliteStore,
  options: {
    serializer: 'json',
    ttl: ONE_MINUTE * 60
  }
});


async function getCollectionsInfoFromCache() {
  const cacheStore = await cacheCollectionStore;

  // Launch error
  const dataCache = await cacheStore.get('foo');
}
```

Error image

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/39039038/219844310-768d79de-15e9-4332-aa1f-efcd5db83598.png">

Node 16.x
Strapi v4

**Comment by maxpert** [comment]
I think your problem is

 >   const cacheStore = await cacheCollectionStore;

You don't that line, and I wonder where did you get that line from?

**Comment by iamveekthorr** [comment]
> This error is happend
> 
> 
> 
> ```js
> 
> const cacheCollectionSQLiteStore = cacheManager.caching({
> 
>   store: sqliteStore,
> 
>   options: {
> 
>     serializer: 'json',
> 
>     ttl: ONE_MINUTE * 60
> 
>   }
> 
> });
> 
> 
> 
> 
> 
> async function getCollectionsInfoFromCache() {
> 
>   const cacheStore = await cacheCollectionStore;
> 
> 
> 
>   // Launch error
> 
>   const dataCache = await cacheStore.get('foo');
> 
> }
> 
> ```
> 
> 
> 
> Error image
> 
> 
> 
> <img width="1225" alt="image" src="https://user-images.githubusercontent.com/39039038/219844310-768d79de-15e9-4332-aa1f-efcd5db83598.png">
> 
> 
> 
> Node 16.x
> 
> Strapi v4
> 
> 

I have the same issue using the package. 

Please does anyone have a solution?.
I'm using nestjs.

**Comment by rivaslive** [comment]
> I think your problem is
> 
> > const cacheStore = await cacheCollectionStore;
> 
> You don't that line, and I wonder where did you get that line from?

Without the await cacheStore.get() is `undefined` because `cacheCollectionStore` is a promise and doesn't have the methods resolved yet

**Comment by iamveekthorr** [comment]
> > I think your problem is
> > > const cacheStore = await cacheCollectionStore;
> > 
> > 
> > You don't that line, and I wonder where did you get that line from?
> 
> Without the await cacheStore.get() is `undefined` because `cacheCollectionStore` is a promise and doesn't have the methods resolved yet


i have fixed mine. 

```bash
CacheModule.registerAsync({
      isGlobal: true,
      useFactory: () => {
        const options = {
          store: sqliteStore,
          name: 'cache',
          path: `cache.db`,
        };
       return caching(options);
      },
    }),
```

this worked for me.

**Comment by rivaslive** [comment]
> 
Unfortunately I still have the same problem in Strapi :(

**Comment by rivaslive** [comment]
> > > I think your problem is
> > > > const cacheStore = await cacheCollectionStore;
> > > 
> > > 
> > > You don't that line, and I wonder where did you get that line from?
> > 
> > 
> > Without the await cacheStore.get() is `undefined` because `cacheCollectionStore` is a promise and doesn't have the methods resolved yet
> 
> i have fixed mine.
> 
> ```shell
> CacheModule.registerAsync({
>       isGlobal: true,
>       useFactory: () => {
>         const options = {
>           store: sqliteStore,
>           name: 'cache',
>           path: `cache.db`,
>         };
>        return caching(options);
>       },
>     }),
> ```
> 
> this worked for me.

Unfortunately I still have the same problem in Strapi. I guess this code is only for Nestjs?

**Comment by maxpert** [comment]
> ```js
> cacheManager.caching
> ```

I have not used strapi, so I have two questions:

 - In `cacheManager.caching` is the `cacheManager` the cache manager coming from `require('cache-manager')`?
 - If no, what is it?

In case it's standard cache-manager package then:

```
const cache = cacheManager.caching({
    store: sqliteStore,
    name: 'employees',
    path: '/tmp/cache.db'
})
```

should give you `cache` with `get` method you are looking for. What is confusing me is 

```
  const cacheStore = await cacheCollectionStore;
```

Is it part of some new standard I am not aware of?

**Comment by rivaslive** [comment]
This is the complete code.

```js
const cacheCollectionSQLiteStore = cacheManager.caching({
    store: sqliteStore,
    options: {
      serializer: 'json',
      ttl: 60 * 60
    }
  });

  const dataCache = await cacheCollectionSQLiteStore.get('key_here');
```

This is error received. What am I doing wrong?

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/39039038/221100401-b5a102d4-a848-4bdf-8602-d3aa3b2767dc.png">

**Comment by rivaslive** [comment]
> > ```js
> > cacheManager.caching
> > ```
> 
> I have not used strapi, so I have two questions:
> 
> * In `cacheManager.caching` is the `cacheManager` the cache manager coming from `require('cache-manager')`?
> * If no, what is it?
> 
> In case it's standard cache-manager package then:
> 
> ```
> const cache = cacheManager.caching({
>     store: sqliteStore,
>     name: 'employees',
>     path: '/tmp/cache.db'
> })
> ```
> 
> should give you `cache` with `get` method you are looking for. What is confusing me is
> 
> ```
>   const cacheStore = await cacheCollectionStore;
> ```
> 
> Is it part of some new standard I am not aware of?

This is the complete code.

```js
const cacheCollectionSQLiteStore = cacheManager.caching({
    store: sqliteStore,
    options: {
      serializer: 'json',
      ttl: 60 * 60
    }
  });

  const dataCache = await cacheCollectionSQLiteStore.get('key_here');
```

This is error received. What am I doing wrong?

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/39039038/221100401-b5a102d4-a848-4bdf-8602-d3aa3b2767dc.png">

**Comment by maxpert** [comment]
> > > ```js
> > > cacheManager.caching
> > > ```
> > 
> > 
> > I have not used strapi, so I have two questions:
> > 
> > * In `cacheManager.caching` is the `cacheManager` the cache manager coming from `require('cache-manager')`?
> > * If no, what is it?
> > 
> > In case it's standard cache-manager package then:
> > ```
> > const cache = cacheManager.caching({
> >     store: sqliteStore,
> >     name: 'employees',
> >     path: '/tmp/cache.db'
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should give you `cache` with `get` method you are looking for. What is confusing me is
> > ```
> >   const cacheStore = await cacheCollectionStore;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it part of some new standard I am not aware of?
> 
> This is the complete code.
> 
> ```js
> const cacheCollectionSQLiteStore = cacheManager.caching({
>     store: sqliteStore,
>     options: {
>       serializer: 'json',
>       ttl: 60 * 60
>     }
>   });
> 
>   const dataCache = await cacheCollectionSQLiteStore.get('key_here');
> ```
> 
> This is error received. What am I doing wrong?
> 
> <img alt="image" width="1268" src="https://user-images.githubusercontent.com/39039038/221100401-b5a102d4-a848-4bdf-8602-d3aa3b2767dc.png">

I think I was not clear enough what is `cacheManager`?  How was it initialized?

**Comment by maxpert** [comment]
I think I figured out the issue. You are using `cache-manager` with v5 or higher. I noticed they have changed everything thing in v5 onwards, which might be causing the issue. I will get package updated and push out a new version with version v5 support.

**Comment by rivaslive** [comment]
> I think I figured out the issue. You are using `cache-manager` with v5 or higher. I noticed they have changed everything thing in v5 onwards, which might be causing the issue. I will get package updated and push out a new version with version v5 support.

cacheManager is default import from 'cache-manager';

**Comment by rivaslive** [comment]
> I think I figured out the issue. You are using `cache-manager` with v5 or higher. I noticed they have changed everything thing in v5 onwards, which might be causing the issue. I will get package updated and push out a new version with version v5 support.

I think that's the real problem, thanks for your good job. Blessings!
